name: firebase_remote_config_hybrid_example
description: Example on using firebase_remote_config_hybrid.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_web_plugins:
    sdk: flutter
  firebase_remote_config_hybrid:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true